name: Security Scan

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install safety
        run: |
          python -m pip install --upgrade pip
          pip install safety

      - name: Run safety check
        run: |
          safety check

